// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HebianGu.Demo.EFCore.MoveDBForMySql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190513101011_changecity")]
    partial class changecity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("ClassLibrary1.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Citys");
                });
#pragma warning restore 612, 618
        }
    }
}
