// <auto-generated />
using System;
using HebianGu.Demo.EFCore.MoveDBForSQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HebianGu.Demo.EFCore.MoveDBForSQLite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190621031821_initsqlite")]
    partial class initsqlite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10");

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Childs");
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CDate");

                    b.Property<int>("Count");

                    b.Property<string>("Group");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Citys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Count = 0,
                            Name = "成都"
                        },
                        new
                        {
                            Id = 5,
                            CDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Count = 0,
                            Name = "北京"
                        });
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Desks");
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.RelationShip", b =>
                {
                    b.Property<int>("ChildID");

                    b.Property<int>("ParentID");

                    b.HasKey("ChildID", "ParentID");

                    b.HasIndex("ParentID");

                    b.ToTable("RelationShips");
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DeskID");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DeskID")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SchoolID");

                    b.HasKey("Id");

                    b.HasIndex("SchoolID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.RelationShip", b =>
                {
                    b.HasOne("HebianGu.Demo.EFCore.MoveDBForSQLite.Child", "Child")
                        .WithMany("RelationShips")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HebianGu.Demo.EFCore.MoveDBForSQLite.Parent", "Parent")
                        .WithMany("RelationShips")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.Student", b =>
                {
                    b.HasOne("HebianGu.Demo.EFCore.MoveDBForSQLite.Desk", "Desk")
                        .WithOne("Student")
                        .HasForeignKey("HebianGu.Demo.EFCore.MoveDBForSQLite.Student", "DeskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HebianGu.Demo.EFCore.MoveDBForSQLite.Teacher", b =>
                {
                    b.HasOne("HebianGu.Demo.EFCore.MoveDBForSQLite.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
